#!/usr/bin/env python3
"""Saca la configuración de Firebase del control de versiones de un repo.

`google-services.json` y `firebase_options.dart` llevan las claves de API del
proyecto. Son config de cliente (Google las diseña para ir embebidas en la app),
pero fuera del repositorio nadie puede usarlas contra la cuota del proyecto.

Deja la copia local intacta, la agrega a .gitignore y guarda una plantilla
`.example` con los valores reemplazados por marcadores.

Uso:  python3 sacar_firebase_de_git.py <repo> [<repo> ...]
"""
import json
import re
import subprocess
import sys
from pathlib import Path

R = Path('/home/cristian/X/Github')
ARCHIVOS = ['android/app/google-services.json', 'lib/firebase_options.dart',
            'ios/Runner/GoogleService-Info.plist', 'macos/Runner/GoogleService-Info.plist']
MARCADORES = {'current_key': 'TU_API_KEY', 'project_id': 'TU_PROJECT_ID',
              'project_number': 'TU_PROJECT_NUMBER', 'mobilesdk_app_id': 'TU_MOBILESDK_APP_ID',
              'client_id': 'TU_CLIENT_ID', 'storage_bucket': 'TU_STORAGE_BUCKET'}
IGNORE = """
# Configuración de Firebase: contiene las claves de API del proyecto.
# Se regenera con `flutterfire configure` (ver README).
android/app/google-services.json
ios/Runner/GoogleService-Info.plist
macos/Runner/GoogleService-Info.plist
lib/firebase_options.dart
"""


def limpiar_json(o):
    if isinstance(o, dict):
        return {k: (MARCADORES[k] if k in MARCADORES else limpiar_json(v)) for k, v in o.items()}
    if isinstance(o, list):
        return [limpiar_json(x) for x in o]
    return o


def limpiar_dart(s):
    s = re.sub(r"(apiKey|appId|messagingSenderId|projectId|storageBucket|authDomain|"
               r"measurementId|iosBundleId|androidClientId|iosClientId):\s*'[^']*'",
               lambda m: f"{m.group(1)}: 'TU_{m.group(1).upper()}'", s)
    return s.replace('// File generated by FlutterFire CLI.',
                     '// PLANTILLA. El archivo real no se versiona: contiene las claves del\n'
                     '// proyecto. Genera el tuyo con `flutterfire configure`.')


def procesar(nombre):
    repo = R / nombre
    git = ['git', '-C', str(repo)]
    hechos = []
    for rel in ARCHIVOS:
        f = repo / rel
        if not f.exists():
            continue
        versionado = subprocess.run(git + ['ls-files', '--error-unmatch', rel],
                                    capture_output=True).returncode == 0
        if not versionado:
            continue
        ej = f.with_suffix(f.suffix + '.example')
        if rel.endswith('.json'):
            ej.write_text(json.dumps(limpiar_json(json.loads(f.read_text())), indent=2) + '\n')
        elif rel.endswith('.dart'):
            ej.write_text(limpiar_dart(f.read_text()))
        subprocess.run(git + ['rm', '--cached', '-q', rel], check=True)
        hechos.append(rel)
    if not hechos:
        print(f'{nombre:16s} sin configuración de Firebase versionada')
        return False
    gi = repo / '.gitignore'
    if 'google-services.json' not in gi.read_text():
        gi.write_text(gi.read_text().rstrip('\n') + '\n' + IGNORE)
    # Que no quede ninguna clave real en las plantillas.
    for rel in hechos:
        t = (repo / (rel + '.example')).read_text()
        assert not re.search(r'AIza[A-Za-z0-9_-]{30,}', t), f'¡clave real en la plantilla de {rel}!'
    print(f'{nombre:16s} desversionados: {", ".join(hechos)}')
    return True


if __name__ == '__main__':
    for n in sys.argv[1:]:
        procesar(n)
